export const BUSINESS_CONFIGS = {
  grocery: {
    label: 'Grocery / Kirana / Provision Shop',
    turnoverMethod: 'itemWise',
    defaultGrossMargin: 25,
    daysPerMonth: 25,
    defaultExpenses: [
      { name: 'Shop Rent', amount: 0 },
      { name: 'Electricity', amount: 0 },
      { name: 'Labor Salary', amount: 0 },
      { name: 'Office Expenses', amount: 2500 },
      { name: 'Transportation', amount: 4000 },
      { name: 'Rates and Taxes', amount: 0 },
      { name: 'Loading and Unloading', amount: 0 },
      { name: 'Telephone Expenses', amount: 2000 },
      { name: 'Repair & Maintenance', amount: 1000 },
      { name: 'Stationery', amount: 0 },
      { name: 'Donations and Pooja', amount: 500 },
      { name: 'Miscellaneous Expenses', amount: 5000 },
      { name: 'Business Promotion', amount: 0 },
      { name: 'Interest on External Borrowings', amount: 0 },
      { name: 'Chits Payment', amount: 0 },
      { name: 'Bank Charges / OD Interest', amount: 0 },
      { name: 'Gold Loan Interest', amount: 0 },
      { name: 'Auto Loan EMI', amount: 0 },
    ],
  },

  dairy: {
    label: 'Dairy Business',
    turnoverMethod: 'sessionWise',
    defaultGrossMargin: 70,
    daysPerMonth: 30,
    sessions: ['Morning', 'Evening'],
    defaultExpenses: [
      { name: 'Shop Rent', amount: 0 },
      { name: 'Electricity', amount: 0 },
      { name: 'Labor Salary', amount: 0 },
      { name: 'Office Expenses', amount: 0 },
      { name: 'Transportation', amount: 2000 },
      { name: 'Rates and Taxes', amount: 0 },
      { name: 'Loading and Unloading', amount: 0 },
      { name: 'Telephone Expenses', amount: 500 },
      { name: 'Repair & Maintenance', amount: 0 },
      { name: 'Stationery', amount: 0 },
      { name: 'Donations and Pooja', amount: 0 },
      { name: 'Miscellaneous Expenses', amount: 0 },
      { name: 'Business Promotion', amount: 5000 },
      { name: 'Interest on External Borrowings', amount: 0 },
      { name: 'Chits Payment', amount: 0 },
      { name: 'Bank Charges / OD Interest', amount: 0 },
      { name: 'Gold Loan Interest', amount: 0 },
      { name: 'Auto Loan EMI', amount: 0 },
    ],
  },

  teaShop: {
    label: 'Tea Shop / Snack Bar',
    turnoverMethod: 'productWise',
    defaultGrossMargin: 50,
    daysPerMonth: 30,
    defaultExpenses: [
      { name: 'Shop Rent', amount: 5000 },
      { name: 'Electricity', amount: 2000 },
      { name: 'Labor Salary', amount: 30000 },
      { name: 'Office Expenses', amount: 0 },
      { name: 'Transportation', amount: 2000 },
      { name: 'Rates and Taxes', amount: 0 },
      { name: 'Loading and Unloading', amount: 0 },
      { name: 'Telephone Expenses', amount: 500 },
      { name: 'Repair & Maintenance', amount: 0 },
      { name: 'Stationery', amount: 0 },
      { name: 'Donations and Pooja', amount: 1000 },
      { name: 'Miscellaneous Expenses', amount: 2000 },
      { name: 'Business Promotion', amount: 3000 },
      { name: 'Interest on External Borrowings', amount: 0 },
      { name: 'Chits Payment', amount: 0 },
      { name: 'Bank Charges / OD Interest', amount: 0 },
      { name: 'Gold Loan Interest', amount: 0 },
      { name: 'Auto Loan EMI', amount: 0 },
    ],
  },

  hotel: {
    label: 'Hotel / Restaurant / Eatery',
    turnoverMethod: 'sessionItemWise',
    defaultGrossMargin: 50,
    daysPerMonth: 25,
    sessions: ['Breakfast', 'Lunch', 'Dinner'],
    defaultExpenses: [
      { name: 'Shop Rent', amount: 20000 },
      { name: 'Electricity', amount: 10000 },
      { name: 'Labor Salary', amount: 80000 },
      { name: 'Office Expenses', amount: 5000 },
      { name: 'Transportation', amount: 5000 },
      { name: 'Rates and Taxes', amount: 5000 },
      { name: 'Loading and Unloading', amount: 5000 },
      { name: 'Telephone Expenses', amount: 1000 },
      { name: 'Repair & Maintenance', amount: 5000 },
      { name: 'Stationery', amount: 0 },
      { name: 'Donations and Pooja', amount: 0 },
      { name: 'Miscellaneous Expenses', amount: 5000 },
      { name: 'Business Promotion', amount: 0 },
      { name: 'Interest on External Borrowings', amount: 0 },
      { name: 'Chits Payment', amount: 0 },
      { name: 'Bank Charges / OD Interest', amount: 0 },
      { name: 'Gold Loan Interest', amount: 0 },
      { name: 'Auto Loan EMI', amount: 0 },
      { name: 'TDS', amount: 0 },
    ],
  },

  tailoring: {
    label: 'Tailoring Business',
    turnoverMethod: 'orderNote',
    defaultGrossMargin: 85,
    daysPerMonth: null,
    defaultExpenses: [
      { name: 'Shop Rent', amount: 5000 },
      { name: 'Electricity', amount: 3000 },
      { name: 'Labor Salary', amount: 20000 },
      { name: 'Office Expenses', amount: 1000 },
      { name: 'Transportation', amount: 1000 },
      { name: 'Rates and Taxes', amount: 0 },
      { name: 'Loading and Unloading', amount: 0 },
      { name: 'Telephone Expenses', amount: 0 },
      { name: 'Repair & Maintenance', amount: 0 },
      { name: 'Stationery', amount: 0 },
      { name: 'Donations and Pooja', amount: 0 },
      { name: 'Miscellaneous Expenses', amount: 0 },
      { name: 'Business Promotion', amount: 0 },
      { name: 'Interest on External Borrowings', amount: 0 },
      { name: 'Chits Payment', amount: 0 },
      { name: 'Bank Charges / OD Interest', amount: 0 },
      { name: 'Gold Loan Interest', amount: 0 },
      { name: 'Auto Loan EMI', amount: 0 },
      { name: 'TDS', amount: 0 },
    ],
  },
};

export const BUSINESS_TYPE_OPTIONS = [
  { value: 'grocery', label: 'Grocery / Kirana / Provision Shop' },
  { value: 'dairy', label: 'Dairy Business' },
  { value: 'teaShop', label: 'Tea Shop / Snack Bar' },
  { value: 'hotel', label: 'Hotel / Restaurant / Eatery' },
  { value: 'tailoring', label: 'Tailoring Business' },
];
